### ISSUE TITLE
格式解析错误：**加粗内容** 内含有中英文冒号结尾的情况，无法完成加粗匹配

### ISSUE THREAD

**Issue by xuweizhan** [pd4d10/bytemd#38]
如下：
```
**加粗内容：**    // 会出现无法解析的问题
**加粗内容:**      // 会出现无法解析的问题
**加粗内容**       // 可以正常解析
```
测试路径：
https://bytemd.js.org/playground/

**Comment by Running53** [comment]
[可以看下这篇文章](https://juejin.cn/post/7064565848421171213#heading-2)，md 语法确实不支持这样书写，但我感觉编译器可以兼容一下，毕竟产品不是面向 md 专家而是普通用户的，不需要对 md 语法有那么深的理解
